install x86 version

diff --git a/de.happyfoto.happyfoto.yml b/de.happyfoto.happyfoto.yml
--- a/de.happyfoto.happyfoto.yml
+++ b/de.happyfoto.happyfoto.yml
@@ -92,9 +92,9 @@ modules:
       - type: extra-data
         only-arches:
           - x86_64
-        url: https://download.microsoft.com/download/D/C/F/DCF5DACB-313F-40C6-889C-AD1F8546099D/IE8-WindowsVista-x64-ENU.exe
-        size: 25492336
-        sha256: 77edee96443514962e4ad2faae95315d75ecfc0ff36b0dc8f7c2a3597018118f
+        url: https://download.microsoft.com/download/F/8/8/F88F09A2-A315-44C0-848E-48476A9E1577/IE8-WindowsVista-x86-ENU.exe
+        size: 13944160
+        sha256: 98c2836a42d1d7a06867022ccc021561241edda8d560b2320db51daf8d58f81d
         filename: ie8-installer.exe
 
       - type: script
@@ -120,66 +120,66 @@ modules:
           - 
           - echo "Performing tweak(s)..."
           - echo "Disable winemenubuilder.exe..."
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v winemenubuilder.exe /d '' /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v winemenubuilder.exe /d '' /f
           -
           - echo "Clear Windows Version"
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ServiceCurrent' /v OS /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\Windows' /v CSDVersion /f
-          - wine64 reg delete 'HKCU\Software\Wine' /v Version /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\ServiceCurrent' /v OS /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\Windows' /v CSDVersion /f
+          - wine reg delete 'HKCU\Software\Wine' /v Version /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
           - 
           - echo "Set Windows Version to Vista"
-          - wine64 reg add 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /d 'WinNT' /f
-          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /d 'Service Pack 2' /f
-          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /d '6002' /f
-          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /d '6.0' /f
-          - wine64 reg add 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows' /v CSDVersion /t REG_DWORD /d 00000200 /
+          - wine reg add 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /d 'WinNT' /f
+          - wine reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /d 'Service Pack 2' /f
+          - wine reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /d '6002' /f
+          - wine reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /d '6.0' /f
+          - wine reg add 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows' /v CSDVersion /t REG_DWORD /d 00000200 /
           - 
           - echo "Clear Windows Version"
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ServiceCurrent' /v OS /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\Windows' /v CSDVersion /f
-          - wine64 reg delete 'HKCU\Software\Wine' /v Version /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\ServiceCurrent' /v OS /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\Windows' /v CSDVersion /f
+          - wine reg delete 'HKCU\Software\Wine' /v Version /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
           - 
           - echo "Set Windows Version to Vista"
-          - wine64 reg add 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /d 'WinNT' /f
-          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /d 'Service Pack 2' /f
-          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /d '6002' /f
-          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /d '6.0' /f
-          - wine64 reg add 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows' /v CSDVersion /t REG_DWORD /d 00000200 /f
+          - wine reg add 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /d 'WinNT' /f
+          - wine reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /d 'Service Pack 2' /f
+          - wine reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /d '6002' /f
+          - wine reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /d '6.0' /f
+          - wine reg add 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows' /v CSDVersion /t REG_DWORD /d 00000200 /f
           - 
-          - source /app/lib/extension/msls31/bin/msls31-install64
+          - source /app/lib/extension/msls31/bin/msls31-install32
           - 
           - echo "Override DLLs"
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v itircl /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v itss /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v jscript /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v msctf /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v mshtml /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v shdoclc /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v shdocvw /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v shlwapi /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v urlmon /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v wininet /d native,builtin /f
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v xmllite /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v itircl /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v itss /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v jscript /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v msctf /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v mshtml /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v shdoclc /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v shdocvw /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v shlwapi /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v urlmon /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v wininet /d native,builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v xmllite /d native,builtin /f
           - 
           - echo "Override iexplorer.exe"
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v iexplore.exe /d native /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v iexplore.exe /d native /f
           - 
           - echo "Override updspapi"
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v updspapi /d builtin /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v updspapi /d builtin /f
           - 
           - echo "Remove builtin iexplore.exe"
           - if [ -f "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Internet Explorer/iexplore.exe" ] ; then
@@ -197,31 +197,32 @@ modules:
           - done
           - 
           - echo "Installing application..."
-          - wine64 "/app/extra/ie8-installer.exe" #"/quiet"
+          - wine "/app/extra/ie8-installer.exe" #"/quiet"
           - 
           - # https://bugs.winehq.org/show_bug.cgi?id=25648
           - echo "Avoid hang, set TabProcGrowth=0"
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main' /v TabProcGrowth /t REG_DWORD /d 00000000 /f
+          - wine reg add 'HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main' /v TabProcGrowth /t REG_DWORD /d 00000000 /f
           - 
           - echo "Clear Windows Version"
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /f
-          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ServiceCurrent' /v OS /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\Windows' /v CSDVersion /f
-          - wine64 reg delete 'HKCU\Software\Wine' /v Version /f
-          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /f
+          - wine reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\ServiceCurrent' /v OS /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\Windows' /v CSDVersion /f
+          - wine reg delete 'HKCU\Software\Wine' /v Version /f
+          - wine reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
           - 
           - echo "Installer finished"
+
       - type: script
         only-arches:
           - x86_64
         dest-filename: ie8
         commands:
-          - export WINEARCH=win64
+          - export WINEARCH=win32
           - 
           - if ! [ -e "${WINEPREFIX}/dosdevices/c:/Program Files/Internet Explorer" ] ; then
           - '    source /app/bin/ie8-installer'
@@ -231,7 +232,7 @@ modules:
           - '    fi'
           - fi
           - 
-          - wine64 "C:\Program Files\Internet Explorer\iexplore.exe"
+          - wine "C:\Program Files\Internet Explorer\iexplore.exe"
       - type: script
         dest-filename: happyfoto-designer-installer
         commands:
@@ -246,7 +247,7 @@ modules:
           - '    exit 1'
           - fi
           - 
-          - echo "Downloading installer..."
+          - echo "Downloading happyfoto-designer installer..."
           - curl -L --progress-bar --output "${XDG_CACHE_HOME}/HappyFoto-Designer.exe" "https://downloads.poi.de/HappyFoto/Windows/DE/HappyFoto-Designer.exe"
           - 
           - echo "Setting-up wine prefix..."
@@ -273,7 +274,7 @@ modules:
       - type: script
         dest-filename: HappyFoto-Designer
         commands:
-          - export WINEARCH=win64
+          - export WINEARCH=win32
           - 
           - if ! [ -e "${WINEPREFIX}/dosdevices/c:/Program Files/HappyFoto-Designer/HappyFoto-Designer.exe" ] ; then
           - '    source /app/bin/happyfoto-designer-installer'
@@ -282,8 +283,13 @@ modules:
           - '        exit 1'
           - '    fi'
           - fi
-          - 
-          - source /app/bin/ie8
+          - if ! [ -e "${WINEPREFIX}/dosdevices/c:/Program Files/Internet Explorer/iexplore.exe" ] ; then
+          - '    source /app/bin/ie8-installer'
+          - '    if [[ $? != 0 ]] ; then'
+          - '        echo "Installation failed, abort."'
+          - '        exit 1'
+          - '    fi'
+          - fi
           - wine "C:/Program Files/HappyFoto-Designer/HappyFoto-Designer.exe" "{@:--SkipBuildPatchPrereq -opengl}"
       - type: file
         path: de.happyfoto.happyfoto.appdata.xml
