add ie8

diff --git a/de.happyfoto.happyfoto.yml b/de.happyfoto.happyfoto.yml
--- a/de.happyfoto.happyfoto.yml
+++ b/de.happyfoto.happyfoto.yml
@@ -75,6 +75,8 @@ modules:
       - install -d /app/bin
       - install happyfoto-designer-installer /app/bin
       - install HappyFoto-Designer /app/bin
+      - install ie8-installer /app/bin
+      - install ie8 /app/bin
       - install -Dm644 de.happyfoto.happyfoto.appdata.xml /app/share/metainfo/de.happyfoto.happyfoto.appdata.xml
       - install -Dm644 de.happyfoto.happyfoto.desktop /app/share/applications/de.happyfoto.happyfoto.desktop
       - install -Dm644 16x16.png /app/share/icons/hicolor/16x16/apps/de.happyfoto.happyfoto.png
@@ -87,6 +89,149 @@ modules:
       - install -Dm664 96x96.png /app/share/icons/hicolor/96x96/apps/de.happyfoto.happyfoto.png
       - install -Dm664 128x128.png /app/share/icons/hicolor/128x128/apps/de.happyfoto.happyfoto.png
     sources:
+      - type: extra-data
+        only-arches:
+          - x86_64
+        url: https://download.microsoft.com/download/D/C/F/DCF5DACB-313F-40C6-889C-AD1F8546099D/IE8-WindowsVista-x64-ENU.exe
+        size: 25492336
+        sha256: 77edee96443514962e4ad2faae95315d75ecfc0ff36b0dc8f7c2a3597018118f
+        filename: ie8-installer.exe
+
+      - type: script
+        only-arches:
+          - x86_64
+        dest-filename: ie8-installer
+        commands:
+          - if [ -z "$WINEPREFIX" ] ; then
+          - '    echo "No wine prefix set or is empty, abort."'
+          - '    exit 1'
+          - fi
+          - 
+          - if [ -e "${WINEPREFIX}/dosdevices/c:/Program Files/Internet Explorer" ] ; then
+          - '    echo "This prefix already has an exisiting ''Internet Explorer 8'' install at ${WINEPREFIX}"'
+          - '    echo "In order to install ''Internet Explorer 8'' you must move or delete the current prefix."'
+          - '    exit 1'
+          - fi
+          - 
+          - echo "Setting-up wine prefix..."
+          - wineboot
+          - 
+          - echo "Installing Extension(s)..."
+          - 
+          - echo "Performing tweak(s)..."
+          - echo "Disable winemenubuilder.exe..."
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v winemenubuilder.exe /d '' /f
+          -
+          - echo "Clear Windows Version"
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ServiceCurrent' /v OS /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\Windows' /v CSDVersion /f
+          - wine64 reg delete 'HKCU\Software\Wine' /v Version /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - 
+          - echo "Set Windows Version to Vista"
+          - wine64 reg add 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /d 'WinNT' /f
+          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /d 'Service Pack 2' /f
+          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /d '6002' /f
+          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /d '6.0' /f
+          - wine64 reg add 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows' /v CSDVersion /t REG_DWORD /d 00000200 /
+          - 
+          - echo "Clear Windows Version"
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ServiceCurrent' /v OS /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\Windows' /v CSDVersion /f
+          - wine64 reg delete 'HKCU\Software\Wine' /v Version /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - 
+          - echo "Set Windows Version to Vista"
+          - wine64 reg add 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /d 'WinNT' /f
+          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /d 'Service Pack 2' /f
+          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /d '6002' /f
+          - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /d '6.0' /f
+          - wine64 reg add 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows' /v CSDVersion /t REG_DWORD /d 00000200 /f
+          - 
+          - source /app/lib/extension/msls31/bin/msls31-install64
+          - 
+          - echo "Override DLLs"
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v itircl /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v itss /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v jscript /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v msctf /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v mshtml /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v shdoclc /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v shdocvw /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v shlwapi /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v urlmon /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v wininet /d native,builtin /f
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v xmllite /d native,builtin /f
+          - 
+          - echo "Override iexplorer.exe"
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v iexplore.exe /d native /f
+          - 
+          - echo "Override updspapi"
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v updspapi /d builtin /f
+          - 
+          - echo "Remove builtin iexplore.exe"
+          - if [ -f "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Internet Explorer/iexplore.exe" ] ; then
+          - '    mv "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Internet Explorer/iexplore.exe" "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Internet Explorer/iexplore.exe.bak"'
+          - fi
+          - 
+          - echo "Remove builtin DLLs"
+          - remove_dlls=(browseui inseng itircl itss jscript msctf mshtml shdoclc shdocvw shlwapi urlmon)
+          - 
+          - for dll in "${remove_dlls[@]}"
+          - do
+          - '    if [ -f "${WINEPREFIX}/dosdevices/c:/windows/system32/${dll}.dll" ] ; then'
+          - '        mv "${WINEPREFIX}/dosdevices/c:/windows/system32/${dll}.dll" "${WINEPREFIX}/dosdevices/c:/windows/system32/${dll}.dll.bak"'
+          - '    fi'
+          - done
+          - 
+          - echo "Installing application..."
+          - wine64 "/app/extra/ie8-installer.exe" #"/quiet"
+          - 
+          - # https://bugs.winehq.org/show_bug.cgi?id=25648
+          - echo "Avoid hang, set TabProcGrowth=0"
+          - wine64 reg add 'HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main' /v TabProcGrowth /t REG_DWORD /d 00000000 /f
+          - 
+          - echo "Clear Windows Version"
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CSDVersion /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentBuildNumber /f
+          - wine64 reg delete 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ServiceCurrent' /v OS /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\Windows' /v CSDVersion /f
+          - wine64 reg delete 'HKCU\Software\Wine' /v Version /f
+          - wine64 reg delete 'HKLM\System\CurrentControlSet\Control\ProductOptions' /v ProductType /f
+          - 
+          - echo "Installer finished"
+      - type: script
+        only-arches:
+          - x86_64
+        dest-filename: ie8
+        commands:
+          - export WINEARCH=win64
+          - 
+          - if ! [ -e "${WINEPREFIX}/dosdevices/c:/Program Files/Internet Explorer" ] ; then
+          - '    source /app/bin/ie8-installer'
+          - '    if [[ $? != 0 ]] ; then'
+          - '        echo "Installation failed, abort."'
+          - '        exit 1'
+          - '    fi'
+          - fi
+          - 
+          - wine64 "C:\Program Files\Internet Explorer\iexplore.exe"
       - type: script
         dest-filename: happyfoto-designer-installer
         commands:
@@ -123,6 +268,8 @@ modules:
           - wine "${XDG_CACHE_HOME}/HappyFoto-Designer.exe"
           - 
           - echo "Installer finished"
+
+
       - type: script
         dest-filename: HappyFoto-Designer
         commands:
@@ -136,6 +283,7 @@ modules:
           - '    fi'
           - fi
           - 
+          - source /app/bin/ie8
           - wine "C:/Program Files/HappyFoto-Designer/HappyFoto-Designer.exe" "{@:--SkipBuildPatchPrereq -opengl}"
       - type: file
         path: de.happyfoto.happyfoto.appdata.xml
